Web Development/ScorePredictor/ScorePredictor/ScorePredictor/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    #path('djangoAdmin/', admin.site.urls),
    path('football/', include('football.urls'),name='football'),
    path('admin/', include('commonAdmin.urls'),name='commonAdmin'),
    
]

Web Development/ScorePredictor/ScorePredictor/commonAdmin/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'commonAdmin'

urlpatterns = [
    path('',views.index,name='index'),
    path('abc/',views.getMatches,name='getMatches'),
    path('def/',views.storeMatches,name='storeMatches'),
]

Web Development/ScorePredictor/ScorePredictor/football/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'football'

urlpatterns = [
    path('',views.index,name='index'),
]

Web Development/ScorePredictor/ScorePredictor/commonAdmin/models.py
from django.db import models

# Create your models here.

Web Development/ScorePredictor/ScorePredictor/football/models.py
from django.db import models

# Create your models here.

Web Development/ScorePredictor/ScorePredictor/commonAdmin/views.py
from django.shortcuts import render
import urllib.request
from django.db import connection
import requests,json
from django.http import HttpResponseRedirect
# Create your views here.
def index(request) :
	return render(request,'commonAdmin/admin.html')

l = []
m = []
context = {}
def getMatches(request) :
	uri = 'http://api.football-data.org/v2/competitions/'
	headers = { 'X-Auth-Token': 'f376990520ea475b8d1a91341ee2c75a' }
	if request.method == "POST" :
		code = request.POST.get('compCode')
		uri += code + '/matches'
		response = requests.get(uri,headers=headers)
		matches = response.json()['matches']
		del m[:]
		for match in matches :
			if match not in m :
				m.append(match)
		context['matches'] = m
		#context['competitions'] = l
		context['code'] = code
	else :
		response = requests.get(uri,headers=headers)
		competitions = response.json()['competitions']
		del l[:]
		for competition in competitions :
			if competition['plan'] == 'TIER_ONE' :
				if competition not in l :
					l.append(competition)
		context['competitions'] = l
		context['matches'] = None
		context['code'] = None
	
	return render(request,'commonAdmin/admin.html',context)

def storeMatches(request):
	cursor = connection.cursor()
	if request.method == "POST" :
		#print(context['code'])
		allMatches = request.POST.getlist('Match')
		#print(allMatches)
		for match in allMatches :
			compCode = context['code']
			matchId = int(match)
			for i in context['competitions'] :
				if i['code'] == compCode :
					compName = i['name']
					break
			for i in context['matches'] :
				#print(i['id'],match)
				if int(i['id']) == int(match) :
					#print('hello')
					homeId = int(i['homeTeam']['id'])
					homeName = i['homeTeam']['name']
					awayId = int(i['awayTeam']['id'])
					awayName = i['awayTeam']['name']
					status = i['status']
					break
			print(compCode,matchId,compName,homeId,homeName,awayId,awayName)
			cursor.execute("SELECT count(*) from Matches where match_id={}".format(matchId))
			r = cursor.fetchone()
			if (r[0] == 0) :
				cursor.execute("INSERT INTO Matches (match_id,compCode,compName,homeTeam,awayTeam,homeTeamId,awayTeamId,status) values('{}','{}','{}','{}','{}','{}','{}','{}')".format(matchId,compCode,compName,homeName,awayName,homeId,awayId,status))
	cursor.close()
	Next = request.POST.get('next','/')
	#print(Next)
	return HttpResponseRedirect(Next)

Web Development/ScorePredictor/ScorePredictor/football/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.db import connection
import requests,json

def index(request) :
	cursor = connection.cursor()
	uri = 'http://api.football-data.org/v2/matches/'
	headers = { 'X-Auth-Token': 'f376990520ea475b8d1a91341ee2c75a' }
	r = cursor.execute("SELECT * FROM Matches;")
	l = []
	d = {}
	context = {}
	while True :
		x = cursor.fetchone()
		if x == None :
			break
		l.append(x)
	for i in l :
		d['match' + str(i[0])] = {'matchId':i[0],'compCode':i[1],'compName':i[2],'homeName':i[3],'awayName':i[4],"homeId":i[5],'awayId':i[6],'status':i[7]}
		uril = uri + str(i[0])
		response = requests.get(uril,headers=headers)
		#print(response)
		match = response.json()['match']
		status = match['status']
		if status != "SCHEDULED" :
			cursor.execute("UPDATE  Matches set status={}".format(status))
	context['matches'] = d
	# for i in context['matches'] :
	#  	print(context['matches'][i])
	if request.method == "POST" :
		pass
		#cursor.execute("INSERT INTO matches(Home_team,Away_team,Home_score,Away_score) values('{}','{}','{}','{}')".format(HomeTeam,AwayTeam,HomeScore,AwayScore))
	cursor.close()
	return render(request,'football/index.html',context=context)

Web Development/ScorePredictor/ScorePredictor/commonAdmin/templates/commonAdmin/admin.html
<!DOCTYPE html>
<html>
<head>
	<title>Score Predictor</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<style type="text/css">
		body {
			background-image: url("https://previews.123rf.com/images/releon003/releon0031701/releon003170100017/69893854-football-field-soccer-ball-green-grass-stadium-background.jpg");
			background-size: cover;
			background-attachment: fixed;
		}
		.normBtn {
			color: #fff !important;
			background-color: #6c757d !important;
			border-color: #6c757d !important;
		}
		.btnHover {
			color: #fff !important;
			background-color: #5a6268 !important;
			border-color: #545b62 !important;
		}
	</style>
	<script type="text/javascript">
		function selectAll() {
			var match = document.getElementsByName('match');
			var i;
			for (i = 0; i < match.length;i++) {
				if (match[i].firstElementChild.checked == false) {
					match[i].click();
				}
			}
		}
		function unSelectAll() {
			var match = document.getElementsByName('match');
			var i;
			console.log(match)
			for (i = 0; i < match.length;i++) {
				if (match[i].firstElementChild.checked == true) {
					match[i].click();
				}
			}
		}
		function clicking(source) {
			if (source.firstElementChild.checked == false) {
				source.firstElementChild.checked = true;
			}
			else {
				source.firstElementChild.checked = false;
			}
		}
				
		
	</script>
	
</head>
<body>
	<div>
		<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
			<a class="navbar-brand" href="">
			<img src="https://media.istockphoto.com/photos/question-mark-gaming-balls-alphabet-picture-id150942995" width="30" height="30" class="d-inline-block align-top" alt="">
			Sports Predictions
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'football:index' %}">Football <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Cricket</a>
					</li>	
				</ul>
			</div>
		</nav>
	</div>
	<div class="container main-content" style="margin-top: 5%">
		<form class="form" method="POST" action="{% url 'commonAdmin:getMatches' %}" id="competitionForm">
			{% csrf_token %}
			<div class="row form-group">
				<select class="form-control competionSelect" name="compCode" onchange="this.form.submit()">
					<option value="" disabled="" selected="">Select Competition</option>
					{% for competition in competitions %}
					{% if code != null and competition.code == code %}
					<option value="{{ competition.code }}" selected>{{ competition.name }}</option>
					{% else %}
					<option value="{{ competition.code }}">{{ competition.name }}</option>
					{% endif %}
					{% endfor %}
				</select>
			</div>
		</form>
		<form class="form" id="mainContent" method="POST" action="{% url 'commonAdmin:storeMatches' %}">
			{% csrf_token %}	
			{% if matches is not None %}
			<div class="row">
				{% for match in matches %}
					{% if match.status == "SCHEDULED" %}
					<div class="col-6 btn-group-toggle mb-1" data-toggle="button">
						<label class="btn btn-secondary" style="width: 90%;" name="match" for="{{ match.id }}" onclick="clicking(this)">
							<input type="checkbox" data-toggle="button" value="{{ match.id }}" autocomplete="off" id="{{ match.id }}" name="Match">
							{{ match.homeTeam.name }} :: {{ match.awayTeam.name }}
						</label>
					</div>
					{% endif %}
				{% endfor %}
			</div>
			<div class="row">
				<div class="col-4 btn-group-toggle mt-5">
					<button type="button" class="btn btn-info" onclick="selectAll()" style="width: 90%">Select All</button>
				</div>
				<div class="col-4 btn-group-toggle mt-5 mb-5">
					<button type="submit" form="mainContent" class="btn btn-primary" value="submit" style="width: 90%">Submit</button>
				</div>
				<div class="col-4 btn-group-toggle mt-5">
					<button type="reset" class="btn btn-danger" onclick="unSelectAll()" style="width: 90%">Reset</button>
				</div>
				
			</div>
			<input type="hidden" name="next" value="{{ request.path }}">
			{% endif %}
		</form>
	</div>
	<script type="text/javascript">
		function form_submit(test) {
			console.log(test);
			document.getElementById('competitionFormSubmit').click();
		}
	</script>
</body>
</html>

Web Development/ScorePredictor/ScorePredictor/football/templates/football/Select.html
<select id="inputState{{ team }}" name="inputState{{ team }}" class="form-control" style="width: 50%" required="">
	<option selected disabled value="">Choose {{ team }} Team</option>
	<option value="FCB">FC Barcelona</option>
	<option value="RMA">Real Madrid</option>
	<option value="MCI">Manchester City</option>
	<option value="LFC">Liverpool</option>
	<option value="TOT">Tottenham</option>
	<option value="ARS">Arsenal</option>
	<option value="CHE">Chelsea</option>
	<option value="MNU">Manchester United</option>
	<option value="JUV">Juventus</option>
</select>

Web Development/ScorePredictor/ScorePredictor/football/templates/football/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Score Predictor</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<style type="text/css">
		body {
			background-image: url("https://previews.123rf.com/images/releon003/releon0031701/releon003170100017/69893854-football-field-soccer-ball-green-grass-stadium-background.jpg");
			background-size: cover;
			background-attachment: fixed;

		}
		.submitBtn {
			display: block;
			margin: 0 auto;
			width: 25%;
		}
	</style>
	<script type="text/javascript">
		function checkValue(name) {
			var objs = document.getElementByName(name)
			for(var obj in objs) {
				obj.required = "true";
			}
		}
	</script>
</head>
<body>
	<div>
			<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
			<a class="navbar-brand" href="">
			<img src="https://media.istockphoto.com/photos/question-mark-gaming-balls-alphabet-picture-id150942995" width="30" height="30" class="d-inline-block align-top" alt="">
			Sports Predictions
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    			<span class="navbar-toggler-icon"></span>
  			</button>
  			<div class="collapse navbar-collapse" id="navbarSupportedContent">
    			<ul class="navbar-nav mr-auto">
      				<li class="nav-item active">
        				<a class="nav-link" href="#">Football <span class="sr-only">(current)</span></a>
      				</li>
				    <li class="nav-item">
				        <a class="nav-link" href="#">Cricket</a>
				    </li>	
    			</ul>
			</div>
		</nav>
	</div>
	<div class="container main-content" style="margin-top: 5%">
		<form class="form" method="POST" action="/football/">
			{% csrf_token %}
			{% for id,match in matches.items %}
			<div class="row" id="helloId">	
				<div class="form-group col-6 mt-5" dir="rtl" style=" float: right;">
					<div class="alert alert-primary" dir="ltr">
						Home : {{ match.homeName }}
					</div>
					<input class="form-control mt-2" type="number" dir="ltr" style="width: 50%" placeholder="" autocomplete="off" oninput="checkValue(this.name)" name="match{{ match }}" id="{{ match }}:{{ match.homeId }}" min="0">
				</div>
				<div class="form-group col-6 mt-5">
					<div class="alert alert-primary">
						Away : {{ match.awayName }}
					</div>
					<input class="form-control mt-2" type="number" style="width: 50%" placeholder="" name="match{{ match }}" oninput="checkValue(this.name)" autocomplete="off" id="{{ match }}:{{ match.awayId }}" min="0">
				</div>
			</div>
			{% endfor %}
			<div class="row">
				<div class="col">
					<button type="submit" class="btn btn-danger submitBtn mb-3 mt-3 ml-auto" value ="Submit">Submit</button>
				</div>
			</div>
		</form>
	</div>
</body>
</html>